openapi: 3.1.0
info:
  title: AREA-51 API
  version: 1.0.0
  description: API documentation for AREA project
paths:
  /about.json:
    get:
      summary: Get project metadata
      description: Returns metadata about the AREA project including name, version, description and available services.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: AREA-51
                  version:
                    type: string
                    example: 1.0.0
                  description:
                    type: string
                    example: API for AREA project metadata
  /api/register:
    post:
      summary: Register a new user
      description: Register a new user with email, username, and password. Returns the created user's ID upon successful registration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user123@example.com
                  format: email
                username:
                  type: string
                  example: user123
                password:
                  type: string
                  example: pass123
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userID:
                    $ref: '#/components/schemas/ObjectId'
        '400':
          $ref: '#/components/responses/Error400'
        '409':
          $ref: '#/components/responses/Error409'
        '500':
          $ref: '#/components/responses/Error500'
  /api/login:
    post:
      summary: Login a user
      description: Login using either email or username along with password. Returns a JWT token valid for 1 hour upon successful authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: Provide either email or username with password (not both).
              oneOf:
                - type: object
                  required: [email, password]
                  properties:
                    email:
                      type: string
                      format: email
                      example: user123@example.com
                    password:
                      type: string
                      example: pass123
                - type: object
                  required: [username, password]
                  properties:
                    username:
                      type: string
                      example: user123
                    password:
                      type: string
                      example: pass123
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  token:
                    $ref: '#/components/schemas/JWT'
        '400':
          $ref: '#/components/responses/Error400'
        '401':
          $ref: '#/components/responses/Error401'
        '500':
          $ref: '#/components/responses/Error500'

components:
  schemas:
    ObjectId:
      type: string
      format: objectid
      pattern: '^[0-9a-fA-F]{24}$'
      description: |
        MongoDB ObjectID - A 12-byte identifier consisting of:
        - 4-byte timestamp (seconds since Unix epoch)
        - 5-byte random value (unique per machine/process)
        - 3-byte incrementing counter (per process, initialized randomly)
        
        Represented as a 24-character hexadecimal string.
      example: "507f1f77bcf86cd799439011"
      minLength: 24
      maxLength: 24
    JWT:
      type: string
      format: jwt
      pattern: '^[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+$'
      description: JSON Web Token for authentication
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDdmMWY3N2JjZjg2Y2Q3OTk0MzkwMTEiLCJpYXQiOjE2MTYyMzkwMjJ9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    ErrorResponse:
      type: object
      description: Standard error payload
      required:
        - message
      properties:
        message:
          type: string
          description: Human readable error description
          example: Error XXX because of YYY
  responses:
    Error400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Error401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Error403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Error404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Error409:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Error500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
